#!/bin/sh
# Montar sistemas virtuales
mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs -o size=16M tmpfs /tmp

# Copiar sistema a RAM
echo "Copiando sistema a RAM..."
cp -a /bin /sbin /etc /lib /usr /tmp/ 2>/dev/null
cp /welcome /tmp/ 2>/dev/null
mkdir -p /tmp/proc /tmp/sys /tmp/dev /tmp/home /tmp/root /tmp/mnt /tmp/tmp 

# Copy devices
cp -a /dev/* /tmp/dev/

# Pivot to RAM
cd /tmp
mkdir -p oldroot
pivot_root . oldroot

# Remount Virtual Fs
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev 2>/dev/null

exec /bin/sh /etc/init.d/rc2
