#!/bin/sh

mknod -m 620 /dev/tty1 c 4 1 2>/dev/null
mknod -m 620 /dev/tty2 c 4 2 2>/dev/null
mknod -m 620 /dev/tty3 c 4 3 2>/dev/null
mknod -m 620 /dev/tty4 c 4 4 2>/dev/null
mknod -m 620 /dev/tty5 c 4 5 2>/dev/null
mknod -m 620 /dev/tty6 c 4 6 2>/dev/null

# PTY support for terminals (st, xterm, etc)
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

# Input device permissions (for X)
chmod 666 /dev/input/* 2>/dev/null
chmod 666 /dev/tty* 2>/dev/null

# Desmontar floppy
umount /oldroot/sys 2>/dev/null
umount /oldroot/proc 2>/dev/null
umount /oldroot/dev 2>/dev/null
umount /oldroot 2>/dev/null
rmdir /oldroot 2>/dev/null

# Load Network Card Module
modprobe 8139too

# Configure network
ifconfig lo 127.0.0.1
ifconfig eth0 192.168.100.99 netmask 255.255.255.0
hostname ginebra

#modules
modprobe psmouse

# Environment variables (heredadas por los shells)
export HOME=/root
export TERM=linux
export PATH=/bin:/sbin:/usr/bin:/usr/sbin
export DISPLAY=:0

echo "Ginebra Linux running from RAM"
clear
cat /welcome
